### ISSUE TITLE
I can't use this project to build godot project...

### ISSUE THREAD

**Issue by colorworlds** [acedogblast/ProjectUraniumAutoBuilder#2]
I use the 0.2 version to build the godot project,but the command line prompts the following error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/acedogblast/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

```
It looks like the problem  caused by  version of JRE. I don't know Java,So I'm not sure.
This is my java version information:
```
E:\>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)
```

This is my command:
```
E:\demo-project\poke-demo>java -jar ProjectUraniumAutoBuilder.jar D:\Games\Pokemon Uranium Team\Pokemon Uranium 1.0 E:\demo-project\poke-demo\Project-Uranium-Godot D:\Program Files\ffmpeg\bin\ffmpeg.exe
```
I'm not sure what went wrong
Can you provide some solutions? This is really  too difficult for a rookie.

**Comment by acedogblast** [comment]
Sorry for the difficulty. I see you are really interested in the project. I will upload a new jar so that it should work with java 8. Thanks for bringing this up.

**Comment by acedogblast** [comment]
Ok please redownload the jar file and try again. Also you need to download the latest version of uranium (v1.2.4). Use this command:
E:\demo-project\poke-demo>java -jar ProjectUraniumAutoBuilder.jar "D:\Games\Pokemon Uranium Team\Pokemon Uranium 1.0" "E:\demo-project\poke-demo\Project-Uranium-Godot" "D:\Program Files\ffmpeg\bin\ffmpeg.exe"

**Comment by acedogblast** [comment]
For paths that include spaces you need to surround them with double quotes. After this finishes you should be able to open the project in Godot and build it.

**Comment by colorworlds** [comment]
> For paths that include spaces you need to surround them with double quotes. After this finishes you should be able to open the project in Godot and build it.

Thank you very much for your help!
